// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXkAAfgTZS3r-hmR7Z1dDQryxf4TeVnB0',
    appId: '1:924582177884:web:189ae4d0646091e4faca99',
    messagingSenderId: '924582177884',
    projectId: 'haribaskar-portfolio',
    authDomain: 'haribaskar-portfolio.firebaseapp.com',
    storageBucket: 'haribaskar-portfolio.firebasestorage.app',
    measurementId: 'G-F70628DE2Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB92Ncq6mNZQ3j3PeRCerZFkyTUPM0X5aw',
    appId: '1:924582177884:ios:8669bd5855d3ee00faca99',
    messagingSenderId: '924582177884',
    projectId: 'haribaskar-portfolio',
    storageBucket: 'haribaskar-portfolio.firebasestorage.app',
    iosBundleId: 'com.praveen.praveenWebsite',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB92Ncq6mNZQ3j3PeRCerZFkyTUPM0X5aw',
    appId: '1:924582177884:ios:8669bd5855d3ee00faca99',
    messagingSenderId: '924582177884',
    projectId: 'haribaskar-portfolio',
    storageBucket: 'haribaskar-portfolio.firebasestorage.app',
    iosBundleId: 'com.praveen.praveenWebsite',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMdHWZQwxgZ-_IsNyQP3x5Cr69YX232aI',
    appId: '1:924582177884:android:d03a47c53822a747faca99',
    messagingSenderId: '924582177884',
    projectId: 'haribaskar-portfolio',
    storageBucket: 'haribaskar-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXkAAfgTZS3r-hmR7Z1dDQryxf4TeVnB0',
    appId: '1:924582177884:web:a04c29e3c29732b6faca99',
    messagingSenderId: '924582177884',
    projectId: 'haribaskar-portfolio',
    authDomain: 'haribaskar-portfolio.firebaseapp.com',
    storageBucket: 'haribaskar-portfolio.firebasestorage.app',
    measurementId: 'G-7N6GV1FMHL',
  );

}